language: java
dist: xenial
sudo: false

branches:
  except:
    - gh-pages

env:
  global:
    - secure: Ce3oODysULOXpf+LAZgd4j942c5Ck5n7e/Lj0vEzdyMAYXVerraVctrFxlu90aCqqzWuMmlL5f0YWhPUwUFVBxtL0vUUT1g/2w95wix8p7SqkiE+fc//o/DIowGztUJ/5kIn4GMPyx4/RAk/YnYEptc8fpOcqWK52BAPgE9zX39Wmgl08VLwY1x474T3r0NG0YSldj7FUmt/R606DegP3YcqP6Tqwhv3xpp25HNw0qNu3yCJm8gpGCEzRElXBRts2bHU+nnW+BgQrhX+WOSI2UfCr4tDxprq2MP6yvDNZgaiJwJ9quBo4dbgjSKVLrVnQQYnCzaxDN4RuZxvfJVFXx7tim8Y4/ocZU8GZVXgcTBDcSjNUqNAlMZyfdoQEbNzHrFbsCk4KmTKsaAKmMV4MaLX2vFrl8WxLSAEXRboOgq3d+pXRKK/fWMQdG+bWWk0QbbasGb+gNadGgfPbNPh52ikASkRLEwkhJXIS9oU8ZgaXJvrgFmZwbXBqZkhv/ff6/cYHPx0BNR1gLeOnOwrkK67CRHQ2yIF4NWdRXmiZ0w4VmatYbHGaWrpM9/Jy2TOotCjDu3wEuUwZcTrFCma1dn06cUQrlBnxeCIJ/iA4hk7nI4SO1+oM0sXa/YTLxMUXOGV/kPPBcwyJ0DIu5IA6AakTOQNnBF8F5bqUBvlcFc=

addons:
  apt:
    update: true

matrix:
  include:
    - name: "Java 8 Tests"
      jdk: openjdk8
      env: TESTENV=tests
      script: mvn test
    - name: "GitHub Pages"
      jdk: openjdk8
      env: TESTENV=cover FYI="this also builds documentation for tags"
      script: '[[ -n "$TRAVIS_TAG" ]] && ./deploy-docs.sh || true'
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - python-virtualenv
            - make

after_success:
  - '[[ "$TESTENV" == "tests" ]] && bash <(curl -s https://codecov.io/bash) -f engine.io-server-coverage/target/site/jacoco-aggregate/jacoco.xml'

cache:
  directories:
  - $HOME/.m2
